apiVersion: v1
kind: Service
metadata:
  name: "{{ template "polling.ui" . }}"
  labels:
{{ include "polling.labels" . | indent 4 }}
    component: ui
spec:
{{- if eq .Values.expose.type "nodePort" }}
{{- $nodePort := .Values.expose.nodePort }}
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
      {{- if $nodePort.port }}
      nodePort: {{ $nodePort.port }}
      {{- end }}
{{- else -}}
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http
{{- end }}
  selector:
{{ include "polling.matchLabels" . | indent 4 }}
    component: ui
